name: CI build and test

on:
  push:
    branches:
        - initial-commit

#on:
#  pull_request:
#    branches:
#        - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.15.0

    - name: Install dependencies
      run: npm ci

    - name: Running unit tests
      run: npm run test
    
    - name: Running static code analysis test
      run: npm run lint